### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by bansky-cl** [hpzhang94/DiffuSum#1]
when i conduct `pip install -r requirements.txt`,  it ocurrs `ERROR : Could not install packages due to an OSError: [Errno 2]  no such file or path: '/croot/certifi_1665076670883/work/certifi'`,  So I think the install dependency may have something wrong. Perhaps it doesn't need too many packages, could you make it simpler ?

**Comment by hpzhang94** [comment]
please double check the environment setup. We could not reproduce your issue on our EC2 servers.
