### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by forkliu0826** [hpzhang94/DiffuSum#2]
Hello author, I have the following error and ask for advice to solve whether the file is missing。
FileNotFoundError: Unable to find '/content/DiffuSum/./datasets/cnndm/train.jsonl' at /content/DiffuSum

**Comment by hpzhang94** [comment]
Hi, please download the preprocessed data from MatchSum repo: https://github.com/maszhongming/MatchSum and put it in the corresponding directories.
