### ISSUE TITLE
train on PubMed error

### ISSUE THREAD

**Issue by nicknamechiou** [hpzhang94/DiffuSum#4]
Hi, 
When I  used command in ReadMe to train on PubMed 
`python run_train_sum.py --diff_steps 500 --model_arch transformer_sum --lr 1e-5 --seed 101 --noise_schedule sqrt --in_channel 128 --modality roc --submit no --padding_mode pad --app "--predict_xstart True --training_mode e2e --roc_train pubmed " --notes pubmed --bsz 64 --epochs 10`

I got an error: 
`File "./train_sum.py", line 19, in <module>`
`    from imp_diff.improved_diffusion.image_datasets import load_data`
`No module named 'imp_diff.improved_diffusion.image_datasets'`

Where I can find this file 'image_datasets'

**Comment by dontwannagetbald** [comment]
Me2, do u have any ideas now?

**Comment by dontwannagetbald** [comment]
> We reuse the preprocessed data from MatchSum repo: https://github.com/maszhongming/MatchSum . Please download the data and put it in the corresponeding directories.

Where did u put the data and what data did u put btw?

**Comment by nicknamechiou** [comment]
pubmed data, and put into ./datasets/others/
and NO, I STILL DON'T KNOW HOW TO FIX THIS.

**Comment by dontwannagetbald** [comment]
> pubmed data, and put into ./datasets/others/ and NO, I STILL DON'T KNOW HOW TO FIX THIS.

Thank u for ur response. And I've solved the problem by easily delete "from imp_diff.improved_diffusion.image_datasets import load_data". It's not used. And also, another "No module" error would occur, just search that module name online and u will find th e missing file in another github repository.
